config/routes.rb
Trollmemaybe::Application.routes.draw do
  get 'about' => 'pages#about'
  root :to => 'pages#home'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Trollmemaybe</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
			
			<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="#">TrollMeMaybe</a>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      		<ul class="nav">
      	
	           <li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", about_path %></li>
			</ul>
			<ul class="nav pull-right">
      	
	           <li><%= link_to "Login", root_path %></li>
				
			</ul>
      </div>
      </div>
 
    </div>
  </div>
</div>
<div class="container">
		<%= yield %>
		<div class="footer">
			<small>by <%= link_to "suyesh", "http://facebook.com/suyesh" %>
			</small>
		</div>
		</div>

	</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	<%= link_to "trollmemaybe", "http://trollmemaybe.com" %>
	Here you can upload, share and TROLL
</p>

app/views/pages/home.html.erb
<div class="hero-unit">

<h1>Welcome to TrollMeMaybe.com</h1>
<p>
	Feel Free to upload, Share and Troll your friends!!
</p>
<%= link_to "Sign up Now!", "http://trollmemaybe.com/signup", class: "btn btn-primary btn-large" %>

</div>